spring:
  datasource:
    url: ${REPORT_GENERATOR_DB_URL}
    username: ${REPORT_GENERATOR_DB_USERNAME}
    password: ${REPORT_GENERATOR_DB_PASSWORD}
    driver-class-name: ${REPORT_GENERATOR_DRIVER}
app:
  reports:
    directory: ${REPORT_DIRECTORY}